// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jxbqgvuajhbnudurunvi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp4YnFndnVhamhibnVkdXJ1bnZpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5MjMxNDcsImV4cCI6MjA3MDQ5OTE0N30.fTObXG2NTEqTvlcHjkQkB3mTd6rSGRrO_J5ZmbJbCis";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});